
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const databaseUrl = env("DATABASE_URL");
/** Migraciones: en Vercel + Neon usá DIRECT_URL (conexión directa, sin pooler) para evitar P1002 advisory lock timeout. */
const directUrl = process.env.DIRECT_URL ?? databaseUrl;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
    directUrl,
  },
});
